---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.3.15
    hooks:
      - id: biome-check
        name: Check JavaScript with biome
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
        name: Check JSON files with check-json
      - id: check-yaml
        name: Check YAML files with check-yaml
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.1
    hooks:
      - id: check-github-workflows
        name: Check GitHub workflows with check-jsonschema
        args: ["--verbose"]
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.23.1
    hooks:
      - id: zizmor
        name: Check GitHub Actions workflows with zizmor
